### ISSUE TITLE
Reportportal is starting a huge number of connections when using the requests lib in a test

### ISSUE THREAD

**Issue by herrlindahl** [reportportal/client-Python#113]
Hi!

I have been trouble shooting a large amount of the day a found that when using the requests lib in a pytest and issuing a GET request the reportportal_client floods the log with: 
`DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection ...`

I enabled logging in pytest.ini as my testcase seamed to hang (bold row in test_file.py) when running pytest with --reportportal flag. Without using reportportal the test is passing OK.

**pytest.ini**
`[pytest]
rp_endpoint = http://10.46.61.14:8080/
rp_uuid = 67d0585c-9812-439e-9a8a-dece859204c7
rp_launch = Test_framework
rp_project = LHD_PERSONAL
rp_launch_attributes = 'LHD'
log_cli = True
log_level = DEBUG`

**test_file.py**
`import requests
import time
import pytest

def test_one():
    for i in range(6):
        **print(requests.get("http://10.46.100.135:5001/"))**
        time.sleep(1)`

**conftest.py**
from pathlib import Path
import pytest

Using Reportportal: Build: 5.1.0
Using a virtual environment with the following packages installed:
atomicwrites (1.4.0)
attrs (19.3.0)
certifi (2020.4.5.1)
chardet (3.0.4)
dill (0.3.1.1)
idna (2.9)
importlib-metadata (1.6.0)
more-itertools (8.3.0)
packaging (20.4)
pip (9.0.1)
pkg-resources (0.0.0)
pluggy (0.13.1)
py (1.8.1)
pyparsing (2.4.7)
pytest (5.4.2)
pytest-reportportal (5.0.3)
reportportal-client (5.0.3)
requests (2.23.0)
setuptools (39.0.1)
six (1.15.0)
urllib3 (1.25.9)
wcwidth (0.2.2)
zipp (3.1.0)

**LOGG when NOissue occurs (not using reportportal)**
(venv) ubuntu@ubuntu-TMGmlin:~/stash/pytest_lab$ python3 -m pytest /home/ubuntu/stash/pytest_lab/test_file.py
================================================================== test session starts ===================================================================
platform linux -- Python 3.6.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/ubuntu/stash/pytest_lab, inifile: pytest.ini
plugins: reportportal-5.0.3
collected 1 item                                                                                                                                         

test_file.py::test_one 
--------------------------------------------------------------------- live log call ----------------------------------------------------------------------
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.100.135:5001 "GET / HTTP/1.1" 200 35440
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.100.135:5001 "GET / HTTP/1.1" 200 35440
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.100.135:5001 "GET / HTTP/1.1" 200 35440
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.100.135:5001 "GET / HTTP/1.1" 200 35440
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.100.135:5001 "GET / HTTP/1.1" 200 35440
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.100.135:5001 "GET / HTTP/1.1" 200 35440
PASSED                                                                                                                                             [100%]

=================================================================== 1 passed in 6.34s ====================================================================

**LOGG when issue occurs**
(venv) ubuntu@ubuntu-TMGmlin:~/stash/pytest_lab$ python3 -m pytest /home/ubuntu/stash/pytest_lab/test_file.py --reportportal
----------------------------------------------------------------- live log sessionstart ------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:128 ReportPortal - Init service: endpoint=http://10.46.61.14:8080/, project=LHD_PERSONAL, uuid=67d0585c-9812-439e-9a8a-dece859204c7
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "GET /api/v1/LHD_PERSONAL/settings HTTP/1.1" 200 676
DEBUG    reportportal_client.service:service.py:367 settings
DEBUG    pytest_reportportal.service:service.py:160 ReportPortal - Start launch: equest_body={'attributes': [{'value': 'LHD'}, {'key': 'agent', 'value': 'pytest-reportportal-pytest-reportportal 5.0.3', 'system': True}, {'key': 'cpu', 'value': 'x86_64', 'system': True}, {'key': 'machine', 'value': 'x86_64', 'system': True}, {'key': 'os', 'value': 'Linux', 'system': True}], 'name': 'Test_framework', 'start_time': '1591126941056', 'description': '', 'mode': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/launch HTTP/1.1" 201 59
DEBUG    reportportal_client.service:service.py:225 start_launch - ID: 5590b041-8a1b-4c9c-a3d8-dd464cc11cf4
DEBUG    pytest_reportportal.service:service.py:162 ReportPortal - Launch started: id=5590b041-8a1b-4c9c-a3d8-dd464cc11cf4
collected 1 item                                                                                                                                         
------------------------------------------------------------------ live log collection -------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:243 ReportPortal - Start Suite: request_body={'name': 'test_file.py', 'description': None, 'start_time': '1591126941143', 'item_type': 'SUITE', 'parent_item_id': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/item HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:290 start_test_item - ID: 4030c073-cbea-42d5-affc-5435e8e5f2c5
DEBUG    pytest_reportportal.service:service.py:262 ReportPortal - Start TestItem: request_body={'attributes': [], 'name': 'test_one', 'description': None, 'start_time': '1591126941216', 'item_type': 'STEP', 'parent_item_id': '4030c073-cbea-42d5-affc-5435e8e5f2c5', 'parameters': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/item/4030c073-cbea-42d5-affc-5435e8e5f2c5 HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:290 start_test_item - ID: 5e9da4a3-2dde-4e0e-b64b-788919bacfd2

--------------------------------------------------------------------- live log call ----------------------------------------------------------------------
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/log HTTP/1.1" 201 45
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (2): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (3): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (4): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (5): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (6): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (7): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (8): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (9): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (10): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (11): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (12): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (13): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (14): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (15): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (16): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (17): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (18): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (19): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (20): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (21): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (22): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (23): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (24): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (25): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (26): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (27): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (28): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (29): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (30): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (31): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (32): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (33): 10.46.61.14:8080
WARNING  urllib3.connectionpool:connectionpool.py:303 Connection pool is full, discarding connection: 10.46.61.14
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (34): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (35): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (36): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (37): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (38): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (39): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (40): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (41): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (42): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (43): 10.46.61.14:8080
WARNING  urllib3.connectionpool:connectionpool.py:303 Connection pool is full, discarding connection: 10.46.61.14
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (44): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (45): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (46): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (47): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (48): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (49): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (50): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (51): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (52): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (53): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (54): 10.46.61.14:8080
WARNING  urllib3.connectionpool:connectionpool.py:303 Connection pool is full, discarding connection: 10.46.61.14
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (55): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (56): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (57): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (58): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (59): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (60): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (61): 10.46.61.14:8080
.....   and it just keeps on going ....

Any suggestions how to solve this is appreciated. Please let me know i you need more information.

**Comment by herrlindahl** [comment]
One more thing, i changed my test to not do a requests.get() but a simple print() instead. Then the communication towards reportportal work.

`import requests
import time
#import pytest


def test_one():
    for i in range(6):
        # print(requests.get("http://10.46.100.135:5001/"))
        print("Test")
        time.sleep(1)
`

**LOG from working example**
(venv) ubuntu@ubuntu-TMGmlin:~/stash/pytest_lab$ python3 -m pytest /home/ubuntu/stash/pytest_lab/test_file.py --reportportal

----------------------------------------------------------------- live log sessionstart ------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:128 ReportPortal - Init service: endpoint=http://10.46.61.14:8080/, project=LHD_PERSONAL, uuid=67d0585c-9812-439e-9a8a-dece859204c7
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.61.14:8080
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "GET /api/v1/LHD_PERSONAL/settings HTTP/1.1" 200 676
DEBUG    reportportal_client.service:service.py:367 settings
DEBUG    pytest_reportportal.service:service.py:160 ReportPortal - Start launch: equest_body={'attributes': [{'value': 'LHD'}, {'key': 'agent', 'value': 'pytest-reportportal-pytest-reportportal 5.0.3', 'system': True}, {'key': 'cpu', 'value': 'x86_64', 'system': True}, {'key': 'machine', 'value': 'x86_64', 'system': True}, {'key': 'os', 'value': 'Linux', 'system': True}], 'name': 'Test_framework', 'start_time': '1591135120374', 'description': '', 'mode': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/launch HTTP/1.1" 201 59
DEBUG    reportportal_client.service:service.py:225 start_launch - ID: c46aef7a-5225-4a38-97a4-227414ed75dc
DEBUG    pytest_reportportal.service:service.py:162 ReportPortal - Launch started: id=c46aef7a-5225-4a38-97a4-227414ed75dc
collected 1 item                                                                                                                                         
------------------------------------------------------------------ live log collection -------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:243 ReportPortal - Start Suite: request_body={'name': 'test_file.py', 'description': None, 'start_time': '1591135120669', 'item_type': 'SUITE', 'parent_item_id': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/item HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:290 start_test_item - ID: 6dc15770-33fe-4301-bab3-55e9734aa3ca
DEBUG    pytest_reportportal.service:service.py:262 ReportPortal - Start TestItem: request_body={'attributes': [], 'name': 'test_one', 'description': None, 'start_time': '1591135120816', 'item_type': 'STEP', 'parent_item_id': '6dc15770-33fe-4301-bab3-55e9734aa3ca', 'parameters': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "POST /api/v2/LHD_PERSONAL/item/6dc15770-33fe-4301-bab3-55e9734aa3ca HTTP/1.1" 201 45
DEBUG    reportportal_client.service:service.py:290 start_test_item - ID: d174426a-4013-41d3-8b61-b942b6288ecd
PASSED                                                                                                                      [100%]
-------------------------------------------------------------------- live log finish ---------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:279 ReportPortal - Finish TestItem: request_body={'end_time': '1591135126976', 'status': 'PASSED', 'issue': {'issueType': 'ti001'}, 'item_id': 'd174426a-4013-41d3-8b61-b942b6288ecd'}

DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "PUT /api/v2/LHD_PERSONAL/item/d174426a-4013-41d3-8b61-b942b6288ecd HTTP/1.1" 200 93
DEBUG    reportportal_client.service:service.py:346 finish_test_item - ID: d174426a-4013-41d3-8b61-b942b6288ecd
DEBUG    pytest_reportportal.service:service.py:296 ReportPortal - End TestSuite: request_body={'end_time': '1591135127048', 'issue': {'issueType': 'ti001'}, 'item_id': '6dc15770-33fe-4301-bab3-55e9734aa3ca', 'status': 'PASSED'}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "PUT /api/v2/LHD_PERSONAL/item/6dc15770-33fe-4301-bab3-55e9734aa3ca HTTP/1.1" 200 93
DEBUG    reportportal_client.service:service.py:346 finish_test_item - ID: 6dc15770-33fe-4301-bab3-55e9734aa3ca
----------------------------------------------------------------- live log sessionfinish -----------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:309 ReportPortal - Finish launch: request_body={'end_time': '1591135127121', 'status': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 http://10.46.61.14:8080 "PUT /api/v1/LHD_PERSONAL/launch/c46aef7a-5225-4a38-97a4-227414ed75dc/finish HTTP/1.1" 200 124
DEBUG    reportportal_client.service:service.py:240 finish_launch - ID: c46aef7a-5225-4a38-97a4-227414ed75dc


============================== 1 passed in 6.55s ===============================

**Comment by iivanou** [comment]
@herrlindahl Can you try reporting to https://beta.demo.reportportal.io/ instead of http://10.46.61.14:8080?

**Comment by herrlindahl** [comment]
@iivanou 

(venv) ubuntu@ubuntu-TMGmlin:~/stash/pytest_lab$ python3 -m pytest /home/ubuntu/stash/pytest_lab/test_file.py --reportportal

----------------------------------------------------------------- live log sessionstart ------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:128 ReportPortal - Init service: endpoint=https://beta.demo.reportportal.io/, project=herrlindahl_personal, uuid=c0ebaab2-62a3-42fa-9636-0ab7de48dcc6
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (1): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:442 https://beta.demo.reportportal.io:443 "GET /api/v1/herrlindahl_personal/settings HTTP/1.1" 200 None
DEBUG    reportportal_client.service:service.py:367 settings
DEBUG    pytest_reportportal.service:service.py:160 ReportPortal - Start launch: equest_body={'attributes': [{'value': 'LHD'}, {'key': 'agent', 'value': 'pytest-reportportal-pytest-reportportal 5.0.3', 'system': True}, {'key': 'cpu', 'value': 'x86_64', 'system': True}, {'key': 'machine', 'value': 'x86_64', 'system': True}, {'key': 'os', 'value': 'Linux', 'system': True}], 'name': 'herrlindahl_TEST_EXAMPLE', 'start_time': '1591166219574', 'description': '', 'mode': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 https://beta.demo.reportportal.io:443 "POST /api/v2/herrlindahl_personal/launch HTTP/1.1" 201 None
DEBUG    reportportal_client.service:service.py:225 start_launch - ID: 99e009da-7c65-421f-8f51-87122e7720c7
DEBUG    pytest_reportportal.service:service.py:162 ReportPortal - Launch started: id=99e009da-7c65-421f-8f51-87122e7720c7
collected 1 item                                                                                                                                         
------------------------------------------------------------------ live log collection -------------------------------------------------------------------
DEBUG    pytest_reportportal.service:service.py:243 ReportPortal - Start Suite: request_body={'name': 'test_file.py', 'description': None, 'start_time': '1591166219697', 'item_type': 'SUITE', 'parent_item_id': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 https://beta.demo.reportportal.io:443 "POST /api/v2/herrlindahl_personal/item HTTP/1.1" 201 None
DEBUG    reportportal_client.service:service.py:290 start_test_item - ID: ef89a77e-3f68-4dc6-888d-8d4635d802d9
DEBUG    pytest_reportportal.service:service.py:262 ReportPortal - Start TestItem: request_body={'attributes': [], 'name': 'test_one', 'description': None, 'start_time': '1591166219799', 'item_type': 'STEP', 'parent_item_id': 'ef89a77e-3f68-4dc6-888d-8d4635d802d9', 'parameters': None}
DEBUG    urllib3.connectionpool:connectionpool.py:442 https://beta.demo.reportportal.io:443 "POST /api/v2/herrlindahl_personal/item/ef89a77e-3f68-4dc6-888d-8d4635d802d9 HTTP/1.1" 201 None
DEBUG    reportportal_client.service:service.py:290 start_test_item - ID: 8f1e7205-51f3-43cc-b428-b592dc69073a

--------------------------------------------------------------------- live log call ----------------------------------------------------------------------
DEBUG    urllib3.connectionpool:connectionpool.py:230 Starting new HTTP connection (1): 10.46.100.135:5001
DEBUG    urllib3.connectionpool:connectionpool.py:442 https://beta.demo.reportportal.io:443 "POST /api/v2/herrlindahl_personal/log HTTP/1.1" 201 None
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (2): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (3): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (4): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (5): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (6): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (7): beta.demo.reportportal.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:941 Starting new HTTPS connection (8): beta.demo.reportportal.io:443

**Comment by herrlindahl** [comment]
I ran 2 tests, one without using the requests library and one with a requests.get() call.

**Test 1**
```
import requests
import time


def test_one():
    for i in range(6):
        # print(requests.get("http://10.46.100.135:5001/"))
        print("Test")
        time.sleep(1)

```

**Test 2**
```
import requests
import time


def test_one():
    for i in range(6):
        print(requests.get("http://10.46.100.135:5001/"))
        print("Test")
        time.sleep(1)

```

**Comment by iivanou** [comment]
It will be fixed once a new client with non-blocking HTTP requests functionality is released.

**Comment by herrlindahl** [comment]
Ok, so do you have any idea of when that is ? :)

**Comment by iivanou** [comment]
No specific date is set cause it is open source. Meanwhile, you can play with the [max pool size](https://github.com/reportportal/client-Python/blob/master/reportportal_client/service.py#L195).

**Comment by herrlindahl** [comment]
@iivanou 
After some more trouble shooting I have seen that this is not a network issue actually. I looks as it has to do with the pytest_reportportal/listner.  If I force PYTEST_HAS_LOGGING_PLUGIN to False in listner.py it starts to work as expected.....

What happens (at least I think so) is that the logger callback will be called recursively and every time the log is sent to reportportal  in reportportal_client/service.py:log() and that is why we are filling up the connectionpool.

This might be a easier fix than non-blocking HTTP requests or what do you think?

**Comment by Ngaur** [comment]
I am also experiencing the similar issue and making it work by forcing PYTEST_HAS_LOGGING_PLUGIN = false in listener.py 
When we can expect a permanent fix of this?
Because making it False, does not send logs for test steps debug logs in test cases, which I was getting earlier in report portal.

**Comment by iivanou** [comment]
You can implement a non-blocking mechanism that aggregates log messages and sends them out via HTTP to RP. The other option is to wait until it is done by anyone else.

@herrlindahl If u are sure about the root cause, you can provide us with PR that fixes the issue.

**Comment by iivanou** [comment]
@Ngaur, @herrlindahl Can you try the latest version of the pytest agent? I have fixed one issue recently that may resolve this one as well. Thanks.

**Comment by jiridanek** [comment]
@iivanou You mean https://github.com/reportportal/agent-python-pytest/releases/tag/5.0.8? For me, this issue still persists there.

**Comment by jiridanek** [comment]
Default, whatever that is.

**Comment by iivanou** [comment]
@jiridanek Can you increase rp_log_batch_size value to 100? It should solve the problem of making new connections too frequently.

**Comment by jiridanek** [comment]
@iivanou I tried 100 and also 200. Did not help. It (possibly) makes the test run longer without the connectionpool warnings, but it always gets into that

```
PASS     dtestlib.Test:levels.py:57 [root@172.17.0.2]$ PYTHONPATH=/var/dtests /opt/miniconda3/envs/tn/bin/python3 /var/dtests/node_data/do_get_artemis1_broker_state.py /opt/jboss-amq-7 /opt/jboss-amq-7-i0 # ecode:0 (exp. 0), dur.:0.45 
PASS     dtestlib.Test:levels.py:57 [root@172.17.0.2]$ PYTHONPATH=/var/dtests /opt/miniconda3/envs/tn/bin/python3 /var/dtests/node_data/do_get_artemis1_broker_state.py /opt/jboss-amq-7 /opt/jboss-amq-7-i0 # ecode:0 (exp. 0), dur.:0.43 
WARNING  urllib3.connectionpool:connectionpool.py:304 Connection pool is full, discarding connection: reportportal-amq-clients-qe.apps.ocp4.xxx
WARNING  urllib3.connectionpool:connectionpool.py:304 Connection pool is full, discarding connection: reportportal-amq-clients-qe.apps.ocp4.xxx
[... repeats again and again ...]
```

**Comment by iivanou** [comment]
Ok. You are not seeing any improvements because you are not sending logs to RP? Am I right?rp_log_batch size impacts only sending logs.

**Comment by iivanou** [comment]
Can you share debug logs? Thanks. What if increase batch log size to 500?

**Comment by iivanou** [comment]
@jiridanek Let's set batch log size to 100 for now. Could you show me how exactly rp endpoint is specified in your config file?

**Comment by jiridanek** [comment]
Hey, I'm OOO today, so I can't do this interactive debug now. I'll edit the message with my rp config as soon as I dig it out.

**Comment by iivanou** [comment]
@jiridanek Can you apply changes from [here ](https://github.com/reportportal/agent-python-pytest/pull/261)with log batch size set to 100? Let me know how are thing going. Thanks in advance.

**Comment by jiridanek** [comment]
That looks reasonable. It's essentially like my workaround I posted before. 

Is there anything special in my usage of pytest rp or to server setup that is causing this? I don't understand why everybody doesn't have same problem.

(If there's something about my setup, i can ask a colleague for help. The report portal instance is provisioned from a canned shared config.)

**Comment by iivanou** [comment]
I think your tests produce too many logs. In case of slow transport to RP instance, we may see such an effect.

**Comment by jiridanek** [comment]
> I think your tests produce too many logs. In case of slow transport to RP instance, we may see such an effect.

Could be. Tests do produce heaps of logs and the RP instance is located in the USA, whereas I am running the test on my laptop in Europe. I did not have this problem in CI, which is running the tests close to the RP instance (same building).

> @jiridanek Can you apply changes from [here ](https://github.com/reportportal/agent-python-pytest/pull/261)with log batch size set to 100? Let me know how are thing going. Thanks in advance.

I just did that, it worked forr me: connectionpool messages are not printed and test finishes. I used `rp_log_batch_size = 100`.

**Comment by iivanou** [comment]
@jiridanek Thanks for the help in debugging. Closing it now.
